const quotes = [
  "How can you put forth your best fruit if you are not put forth within yourself first?",
  "You can only be in hell with your own permission.",
  "There's not enough room in your mind for some other entity's thoughts.",
  "Men are second only to God, which is something that the forgetting of is the end of your life prematurely. Which is usually at the beginning.",
  "The devil makes work of idle hands.",
  "Become who you are, become who you want to be and who you should be, before you never do.",
  "The only thing you're in control of are your own thoughts.",
  "The only thing the devil wants is for you to suffer like it is.",
  "There is no free will in the world, unless you get less of the world.",
  "The only thing there is in this life is to purify your soul, so that you're not afraid of death.",
  "The angels weep for men and women failing to accept the challenge of integrity.",
  "Truly I tell you, unless you turn and become like children, you will never enter the kingdom of heaven. - Matthew 18:3",
  "When we experience tears, our souls become like babies.",
  "There are no coincidences. Nothing is random.",
  "Fear is not a natural state of man.",
  "Be lucid. Live with intent.",
  "Those who unravel the cube are nailed to the cross.",
  "Forgive them for they know not what they do. - Luke 23:34",
  "The fear of death distresses a man with a guilty conscience, but the man with a good witness within himself longs for death as for life.",
  "Your thoughts determine your life.",
  "Strict adherence to one’s own free will, is the fall.",
  "Each and every action are equally drastic, therefore no action is drastic. So you don't have to look at something as hard to do.",
  "It takes control to be addicted. It takes more control to keep it in you than to push it all out.",
  "Restoration of faith is the knowledge of real free will, which is obedience. Free will is actually obedience, but you are only willing to and enthusiastic of obedience when you have faith to back it up.",
  "You're better off fishing in your own mind.",
  "Lucky is the lion that the human will eat, so that the lion becomes human. And foul is the human that the lion will eat, and the lion still will become human.",
  "No prophet is welcome on his home turf. Doctors don't cure those who know him.",
  "Unrealized creativity is one of the most destructive things in the human psyche.",
  "For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places. - Ephesians 6:12",
  "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours. - Mark 11:24",
  "Love and nurture the reflection in every thought and in everything you see.",
]

export default quotes;